version: '3.8'

services:
  guests:
    build: ./guest-service
    ports:
      - "5001:5000"
    depends_on:
      - main
    environment:
      - MAIN_URL=http://main:5000

  rooms:
    build: ./room-service
    ports:
      - "5002:5000"
    depends_on:
      - main
    environment:
      - MAIN_URL=http://main:5000

  main:
    build: ./main
    ports:
      - "5000:5000"
    environment:
      - GUESTS_URL=http://guests:5000
      - ROOMS_URL=http://rooms:5000
